# Figures

## geom_abline
        

```{r results='asis',echo=FALSE}
 fn.src('geom_abline','ggplot2',hlp.dir)
 ```
        

```{r geom_abline, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_abline
### Title: Reference lines: horizontal, vertical, and diagonal
### Aliases: geom_abline geom_hline geom_vline

### ** Examples

p <- ggplot(mtcars, aes(wt, mpg)) + geom_point()

# Fixed values
p + geom_vline(xintercept = 5)
p + geom_vline(xintercept = 1:5)
p + geom_hline(yintercept = 20)

p + geom_abline() # Can't see it - outside the range of the data
p + geom_abline(intercept = 20)

# Calculate slope and intercept of line of best fit
coef(lm(mpg ~ wt, data = mtcars))
p + geom_abline(intercept = 37, slope = -5)
# But this is easier to do with geom_smooth:
p + geom_smooth(method = "lm", se = FALSE)

# To show different lines in different facets, use aesthetics
p <- ggplot(mtcars, aes(mpg, wt)) +
  geom_point() +
  facet_wrap(~ cyl)

mean_wt <- data.frame(cyl = c(4, 6, 8), wt = c(2.28, 3.11, 4.00))
p + geom_hline(aes(yintercept = wt), mean_wt)

# You can also control other aesthetics
ggplot(mtcars, aes(mpg, wt, colour = wt)) +
  geom_point() +
  geom_hline(aes(yintercept = wt, colour = wt), mean_wt) +
  facet_wrap(~ cyl)



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_abline-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_abline',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_abline-up','geom_abline-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_abline-up','geom_abline-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_bar
        

```{r results='asis',echo=FALSE}
 fn.src('geom_bar','ggplot2',hlp.dir)
 ```
        

```{r geom_bar, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_bar
### Title: Bars charts
### Aliases: geom_bar geom_col stat_count

### ** Examples

# geom_bar is designed to make it easy to create bar charts that show
# counts (or sums of weights)
g <- ggplot(mpg, aes(class))
# Number of cars in each class:
g + geom_bar()
# Total engine displacement of each class
g + geom_bar(aes(weight = displ))

# To show (e.g.) means, you need geom_col()
# And, even more succinctly with geom_col()
df <- data.frame(trt = c("a", "b", "c"), outcome = c(2.3, 1.9, 3.2))
ggplot(df, aes(trt, outcome)) +
  geom_col()
# But geom_point() displays exactly the same information and doesn't
# require the y-axis to touch zero.
ggplot(df, aes(trt, outcome)) +
  geom_point()

# You can also use geom_bar() with continuous data, in which case
# it will show counts at unique locations
df <- data.frame(x = rep(c(2.9, 3.1, 4.5), c(5, 10, 4)))
ggplot(df, aes(x)) + geom_bar()
# cf. a histogram of the same data
ggplot(df, aes(x)) + geom_histogram(binwidth = 0.5)




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_bar-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_bar',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_bar-up','geom_bar-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_bar-up','geom_bar-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_bin2d
        

```{r results='asis',echo=FALSE}
 fn.src('geom_bin2d','ggplot2',hlp.dir)
 ```
        

```{r geom_bin2d, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_bin2d
### Title: Heatmap of 2d bin counts
### Aliases: geom_bin2d stat_bin_2d stat_bin2d

### ** Examples

d <- ggplot(diamonds, aes(x, y)) + xlim(4, 10) + ylim(4, 10)
d + geom_bin2d()

# You can control the size of the bins by specifying the number of
# bins in each direction:
d + geom_bin2d(bins = 10)
d + geom_bin2d(bins = 30)

# Or by specifying the width of the bins
d + geom_bin2d(binwidth = c(0.1, 0.1))



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_bin2d-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_bin2d',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_bin2d-up','geom_bin2d-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_bin2d-up','geom_bin2d-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_blank
        

```{r results='asis',echo=FALSE}
 fn.src('geom_blank','ggplot2',hlp.dir)
 ```
        

```{r geom_blank, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_blank
### Title: Draw nothing
### Aliases: geom_blank

### ** Examples

ggplot(mtcars, aes(wt, mpg))
# Nothing to see here!



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_blank-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_blank',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_blank-up','geom_blank-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_blank-up','geom_blank-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_boxplot
        

```{r results='asis',echo=FALSE}
 fn.src('geom_boxplot','ggplot2',hlp.dir)
 ```
        

```{r geom_boxplot, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_boxplot
### Title: A box and whiskers plot (in the style of Tukey)
### Aliases: geom_boxplot stat_boxplot

### ** Examples

p <- ggplot(mpg, aes(class, hwy))
p + geom_boxplot()
p + geom_boxplot() + geom_jitter(width = 0.2)
p + geom_boxplot() + coord_flip()

p + geom_boxplot(notch = TRUE)
p + geom_boxplot(varwidth = TRUE)
p + geom_boxplot(fill = "white", colour = "#3366FF")
# By default, outlier points match the colour of the box. Use
# outlier.colour to override
p + geom_boxplot(outlier.colour = "red", outlier.shape = 1)

# Boxplots are automatically dodged when any aesthetic is a factor
p + geom_boxplot(aes(colour = drv))

# You can also use boxplots with continuous x, as long as you supply
# a grouping variable. cut_width is particularly useful
ggplot(diamonds, aes(carat, price)) +
  geom_boxplot()
ggplot(diamonds, aes(carat, price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.25)))
ggplot(diamonds, aes(carat, price)) +
  geom_boxplot(aes(group = cut_width(carat, 0.25)), outlier.alpha = 0.1)




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_boxplot-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_boxplot',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_boxplot-up','geom_boxplot-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_boxplot-up','geom_boxplot-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_contour
        

```{r results='asis',echo=FALSE}
 fn.src('geom_contour','ggplot2',hlp.dir)
 ```
        

```{r geom_contour, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_contour
### Title: 2d contours of a 3d surface
### Aliases: geom_contour stat_contour

### ** Examples

#' # Basic plot
v <- ggplot(faithfuld, aes(waiting, eruptions, z = density))
v + geom_contour()

# Or compute from raw data
ggplot(faithful, aes(waiting, eruptions)) +
  geom_density_2d()




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_contour-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_contour',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_contour-up','geom_contour-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_contour-up','geom_contour-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_count
        

```{r results='asis',echo=FALSE}
 fn.src('geom_count','ggplot2',hlp.dir)
 ```
        

```{r geom_count, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_count
### Title: Count overlapping points
### Aliases: geom_count stat_sum

### ** Examples

ggplot(mpg, aes(cty, hwy)) +
 geom_point()

ggplot(mpg, aes(cty, hwy)) +
 geom_count()

# Best used in conjunction with scale_size_area which ensures that
# counts of zero would be given size 0. Doesn't make much different
# here because the smallest count is already close to 0.
ggplot(mpg, aes(cty, hwy)) +
 geom_count() +
 scale_size_area()

# Display proportions instead of counts -------------------------------------
# By default, all categorical variables in the plot form the groups.
# Specifying geom_count without a group identifier leads to a plot which is
# not useful:
d <- ggplot(diamonds, aes(x = cut, y = clarity))
d + geom_count(aes(size = ..prop..))
# To correct this problem and achieve a more desirable plot, we need
# to specify which group the proportion is to be calculated over.
d + geom_count(aes(size = ..prop.., group = 1)) +
  scale_size_area(max_size = 10)

# Or group by x/y variables to have rows/columns sum to 1.
d + geom_count(aes(size = ..prop.., group = cut)) +
  scale_size_area(max_size = 10)
d + geom_count(aes(size = ..prop.., group = clarity)) +
  scale_size_area(max_size = 10)



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_count-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_count',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_count-up','geom_count-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_count-up','geom_count-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_density
        

```{r results='asis',echo=FALSE}
 fn.src('geom_density','ggplot2',hlp.dir)
 ```
        

```{r geom_density, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_density
### Title: Smoothed density estimates
### Aliases: geom_density stat_density

### ** Examples

ggplot(diamonds, aes(carat)) +
  geom_density()

ggplot(diamonds, aes(carat)) +
  geom_density(adjust = 1/5)
ggplot(diamonds, aes(carat)) +
  geom_density(adjust = 5)

ggplot(diamonds, aes(depth, colour = cut)) +
  geom_density() +
  xlim(55, 70)
ggplot(diamonds, aes(depth, fill = cut, colour = cut)) +
  geom_density(alpha = 0.1) +
  xlim(55, 70)




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_density-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_density',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_density-up','geom_density-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_density-up','geom_density-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_density_2d
        

```{r results='asis',echo=FALSE}
 fn.src('geom_density_2d','ggplot2',hlp.dir)
 ```
        

```{r geom_density_2d, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_density_2d
### Title: Contours of a 2d density estimate
### Aliases: geom_density_2d geom_density2d stat_density_2d stat_density2d

### ** Examples

m <- ggplot(faithful, aes(x = eruptions, y = waiting)) +
 geom_point() +
 xlim(0.5, 6) +
 ylim(40, 110)
m + geom_density_2d()



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_density_2d-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_density_2d',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_density_2d-up','geom_density_2d-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_density_2d-up','geom_density_2d-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_dotplot
        

```{r results='asis',echo=FALSE}
 fn.src('geom_dotplot','ggplot2',hlp.dir)
 ```
        

```{r geom_dotplot, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_dotplot
### Title: Dot plot
### Aliases: geom_dotplot

### ** Examples

ggplot(mtcars, aes(x = mpg)) + geom_dotplot()
ggplot(mtcars, aes(x = mpg)) + geom_dotplot(binwidth = 1.5)

# Use fixed-width bins
ggplot(mtcars, aes(x = mpg)) +
  geom_dotplot(method="histodot", binwidth = 1.5)

# Some other stacking methods
ggplot(mtcars, aes(x = mpg)) +
  geom_dotplot(binwidth = 1.5, stackdir = "center")
ggplot(mtcars, aes(x = mpg)) +
  geom_dotplot(binwidth = 1.5, stackdir = "centerwhole")

# y axis isn't really meaningful, so hide it
ggplot(mtcars, aes(x = mpg)) + geom_dotplot(binwidth = 1.5) +
  scale_y_continuous(NULL, breaks = NULL)

# Overlap dots vertically
ggplot(mtcars, aes(x = mpg)) + geom_dotplot(binwidth = 1.5, stackratio = .7)

# Expand dot diameter
ggplot(mtcars, aes(x = mpg)) + geom_dotplot(binwidth = 1.5, dotsize = 1.25)




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_dotplot-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_dotplot',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_dotplot-up','geom_dotplot-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_dotplot-up','geom_dotplot-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_errorbarh
        

```{r results='asis',echo=FALSE}
 fn.src('geom_errorbarh','ggplot2',hlp.dir)
 ```
        

```{r geom_errorbarh, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_errorbarh
### Title: Horizontal error bars
### Aliases: geom_errorbarh

### ** Examples

df <- data.frame(
  trt = factor(c(1, 1, 2, 2)),
  resp = c(1, 5, 3, 4),
  group = factor(c(1, 2, 1, 2)),
  se = c(0.1, 0.3, 0.3, 0.2)
)

# Define the top and bottom of the errorbars

p <- ggplot(df, aes(resp, trt, colour = group))
p + geom_point() +
  geom_errorbarh(aes(xmax = resp + se, xmin = resp - se))
p + geom_point() +
  geom_errorbarh(aes(xmax = resp + se, xmin = resp - se, height = .2))



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_errorbarh-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_errorbarh',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_errorbarh-up','geom_errorbarh-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_errorbarh-up','geom_errorbarh-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_hex
        

```{r results='asis',echo=FALSE}
 fn.src('geom_hex','ggplot2',hlp.dir)
 ```
        

```{r geom_hex, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_hex
### Title: Hexagonal heatmap of 2d bin counts
### Aliases: geom_hex stat_bin_hex stat_binhex

### ** Examples

d <- ggplot(diamonds, aes(carat, price))
d + geom_hex()




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_hex-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_hex',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_hex-up','geom_hex-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_hex-up','geom_hex-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_freqpoly
        

```{r results='asis',echo=FALSE}
 fn.src('geom_freqpoly','ggplot2',hlp.dir)
 ```
        

```{r geom_freqpoly, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_freqpoly
### Title: Histograms and frequency polygons
### Aliases: geom_freqpoly geom_histogram stat_bin

### ** Examples

ggplot(diamonds, aes(carat)) +
  geom_histogram()
ggplot(diamonds, aes(carat)) +
  geom_histogram(binwidth = 0.01)
ggplot(diamonds, aes(carat)) +
  geom_histogram(bins = 200)

# Rather than stacking histograms, it's easier to compare frequency
# polygons
ggplot(diamonds, aes(price, fill = cut)) +
  geom_histogram(binwidth = 500)
ggplot(diamonds, aes(price, colour = cut)) +
  geom_freqpoly(binwidth = 500)

# To make it easier to compare distributions with very different counts,
# put density on the y axis instead of the default count
ggplot(diamonds, aes(price, ..density.., colour = cut)) +
  geom_freqpoly(binwidth = 500)

if (require("ggplot2movies")) {
# Often we don't want the height of the bar to represent the
# count of observations, but the sum of some other variable.
# For example, the following plot shows the number of movies
# in each rating.
m <- ggplot(movies, aes(rating))
m + geom_histogram(binwidth = 0.1)

# If, however, we want to see the number of votes cast in each
# category, we need to weight by the votes variable
m + geom_histogram(aes(weight = votes), binwidth = 0.1) + ylab("votes")

# For transformed scales, binwidth applies to the transformed data.
# The bins have constant width on the transformed scale.
m + geom_histogram() + scale_x_log10()
m + geom_histogram(binwidth = 0.05) + scale_x_log10()

# For transformed coordinate systems, the binwidth applies to the
# raw data. The bins have constant width on the original scale.

# Using log scales does not work here, because the first
# bar is anchored at zero, and so when transformed becomes negative
# infinity. This is not a problem when transforming the scales, because
# no observations have 0 ratings.
m + geom_histogram(boundary = 0) + coord_trans(x = "log10")
# Use boundary = 0, to make sure we don't take sqrt of negative values
m + geom_histogram(boundary = 0) + coord_trans(x = "sqrt")

# You can also transform the y axis.  Remember that the base of the bars
# has value 0, so log transformations are not appropriate
m <- ggplot(movies, aes(x = rating))
m + geom_histogram(binwidth = 0.5) + scale_y_sqrt()
}



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_freqpoly-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_freqpoly',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_freqpoly-up','geom_freqpoly-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_freqpoly-up','geom_freqpoly-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_jitter
        

```{r results='asis',echo=FALSE}
 fn.src('geom_jitter','ggplot2',hlp.dir)
 ```
        

```{r geom_jitter, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_jitter
### Title: Jittered points
### Aliases: geom_jitter

### ** Examples

p <- ggplot(mpg, aes(cyl, hwy))
p + geom_point()
p + geom_jitter()

# Add aesthetic mappings
p + geom_jitter(aes(colour = class))

# Use smaller width/height to emphasise categories
ggplot(mpg, aes(cyl, hwy)) + geom_jitter()
ggplot(mpg, aes(cyl, hwy)) + geom_jitter(width = 0.25)

# Use larger width/height to completely smooth away discreteness
ggplot(mpg, aes(cty, hwy)) + geom_jitter()
ggplot(mpg, aes(cty, hwy)) + geom_jitter(width = 0.5, height = 0.5)



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_jitter-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_jitter',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_jitter-up','geom_jitter-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_jitter-up','geom_jitter-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_crossbar
        

```{r results='asis',echo=FALSE}
 fn.src('geom_crossbar','ggplot2',hlp.dir)
 ```
        

```{r geom_crossbar, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_crossbar
### Title: Vertical intervals: lines, crossbars & errorbars
### Aliases: geom_crossbar geom_errorbar geom_linerange geom_pointrange

### ** Examples

#' # Create a simple example dataset
df <- data.frame(
  trt = factor(c(1, 1, 2, 2)),
  resp = c(1, 5, 3, 4),
  group = factor(c(1, 2, 1, 2)),
  upper = c(1.1, 5.3, 3.3, 4.2),
  lower = c(0.8, 4.6, 2.4, 3.6)
)

p <- ggplot(df, aes(trt, resp, colour = group))
p + geom_linerange(aes(ymin = lower, ymax = upper))
p + geom_pointrange(aes(ymin = lower, ymax = upper))
p + geom_crossbar(aes(ymin = lower, ymax = upper), width = 0.2)
p + geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)

# Draw lines connecting group means
p +
  geom_line(aes(group = group)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)

# If you want to dodge bars and errorbars, you need to manually
# specify the dodge width
p <- ggplot(df, aes(trt, resp, fill = group))
p +
 geom_col(position = "dodge") +
 geom_errorbar(aes(ymin = lower, ymax = upper), position = "dodge", width = 0.25)

# Because the bars and errorbars have different widths
# we need to specify how wide the objects we are dodging are
dodge <- position_dodge(width=0.9)
p +
  geom_col(position = dodge) +
  geom_errorbar(aes(ymin = lower, ymax = upper), position = dodge, width = 0.25)



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_crossbar-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_crossbar',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_crossbar-up','geom_crossbar-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_crossbar-up','geom_crossbar-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_map
        

```{r results='asis',echo=FALSE}
 fn.src('geom_map','ggplot2',hlp.dir)
 ```
        

```{r geom_map, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_map
### Title: Polygons from a reference map
### Aliases: geom_map

### ** Examples

# When using geom_polygon, you will typically need two data frames:
# one contains the coordinates of each polygon (positions),  and the
# other the values associated with each polygon (values).  An id
# variable links the two together

ids <- factor(c("1.1", "2.1", "1.2", "2.2", "1.3", "2.3"))

values <- data.frame(
  id = ids,
  value = c(3, 3.1, 3.1, 3.2, 3.15, 3.5)
)

positions <- data.frame(
  id = rep(ids, each = 4),
  x = c(2, 1, 1.1, 2.2, 1, 0, 0.3, 1.1, 2.2, 1.1, 1.2, 2.5, 1.1, 0.3,
  0.5, 1.2, 2.5, 1.2, 1.3, 2.7, 1.2, 0.5, 0.6, 1.3),
  y = c(-0.5, 0, 1, 0.5, 0, 0.5, 1.5, 1, 0.5, 1, 2.1, 1.7, 1, 1.5,
  2.2, 2.1, 1.7, 2.1, 3.2, 2.8, 2.1, 2.2, 3.3, 3.2)
)

ggplot(values) +
  geom_map(aes(map_id = id), map = positions) +
  expand_limits(positions)
ggplot(values, aes(fill = value)) +
  geom_map(aes(map_id = id), map = positions) +
  expand_limits(positions)
ggplot(values, aes(fill = value)) +
  geom_map(aes(map_id = id), map = positions) +
  expand_limits(positions) + ylim(0, 3)

# Better example
crimes <- data.frame(state = tolower(rownames(USArrests)), USArrests)
crimesm <- reshape2::melt(crimes, id = 1)
if (require(maps)) {
  states_map <- map_data("state")
  ggplot(crimes, aes(map_id = state)) +
    geom_map(aes(fill = Murder), map = states_map) +
    expand_limits(x = states_map$long, y = states_map$lat)

  last_plot() + coord_map()
  ggplot(crimesm, aes(map_id = state)) +
    geom_map(aes(fill = value), map = states_map) +
    expand_limits(x = states_map$long, y = states_map$lat) +
    facet_wrap( ~ variable)
}



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_map-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_map',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_map-up','geom_map-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_map-up','geom_map-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_path
        

```{r results='asis',echo=FALSE}
 fn.src('geom_path','ggplot2',hlp.dir)
 ```
        

```{r geom_path, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_path
### Title: Connect observations
### Aliases: geom_path geom_line geom_step

### ** Examples

# geom_line() is suitable for time series
ggplot(economics, aes(date, unemploy)) + geom_line()
ggplot(economics_long, aes(date, value01, colour = variable)) +
  geom_line()

# geom_step() is useful when you want to highlight exactly when
# the y value chanes
recent <- economics[economics$date > as.Date("2013-01-01"), ]
ggplot(recent, aes(date, unemploy)) + geom_line()
ggplot(recent, aes(date, unemploy)) + geom_step()

# geom_path lets you explore how two variables are related over time,
# e.g. unemployment and personal savings rate
m <- ggplot(economics, aes(unemploy/pop, psavert))
m + geom_path()
m + geom_path(aes(colour = as.numeric(date)))

# Changing parameters ----------------------------------------------
ggplot(economics, aes(date, unemploy)) +
  geom_line(colour = "red")

# Use the arrow parameter to add an arrow to the line
# See ?arrow for more details
c <- ggplot(economics, aes(x = date, y = pop))
c + geom_line(arrow = arrow())
c + geom_line(
  arrow = arrow(angle = 15, ends = "both", type = "closed")
)

# Control line join parameters
df <- data.frame(x = 1:3, y = c(4, 1, 9))
base <- ggplot(df, aes(x, y))
base + geom_path(size = 10)
base + geom_path(size = 10, lineend = "round")
base + geom_path(size = 10, linejoin = "mitre", lineend = "butt")

# NAs break the line. Use na.rm = T to suppress the warning message
df <- data.frame(
  x = 1:5,
  y1 = c(1, 2, 3, 4, NA),
  y2 = c(NA, 2, 3, 4, 5),
  y3 = c(1, 2, NA, 4, 5)
)
ggplot(df, aes(x, y1)) + geom_point() + geom_line()
ggplot(df, aes(x, y2)) + geom_point() + geom_line()
ggplot(df, aes(x, y3)) + geom_point() + geom_line()




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_path-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_path',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_path-up','geom_path-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_path-up','geom_path-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_point
        

```{r results='asis',echo=FALSE}
 fn.src('geom_point','ggplot2',hlp.dir)
 ```
        

```{r geom_point, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_point
### Title: Points
### Aliases: geom_point

### ** Examples

p <- ggplot(mtcars, aes(wt, mpg))
p + geom_point()

# Add aesthetic mappings
p + geom_point(aes(colour = factor(cyl)))
p + geom_point(aes(shape = factor(cyl)))
p + geom_point(aes(size = qsec))

# Change scales
p + geom_point(aes(colour = cyl)) + scale_colour_gradient(low = "blue")
p + geom_point(aes(shape = factor(cyl))) + scale_shape(solid = FALSE)

# Set aesthetics to fixed value
ggplot(mtcars, aes(wt, mpg)) + geom_point(colour = "red", size = 3)




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_point-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_point',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_point-up','geom_point-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_point-up','geom_point-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_polygon
        

```{r results='asis',echo=FALSE}
 fn.src('geom_polygon','ggplot2',hlp.dir)
 ```
        

```{r geom_polygon, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_polygon
### Title: Polygons
### Aliases: geom_polygon

### ** Examples

# When using geom_polygon, you will typically need two data frames:
# one contains the coordinates of each polygon (positions),  and the
# other the values associated with each polygon (values).  An id
# variable links the two together

ids <- factor(c("1.1", "2.1", "1.2", "2.2", "1.3", "2.3"))

values <- data.frame(
  id = ids,
  value = c(3, 3.1, 3.1, 3.2, 3.15, 3.5)
)

positions <- data.frame(
  id = rep(ids, each = 4),
  x = c(2, 1, 1.1, 2.2, 1, 0, 0.3, 1.1, 2.2, 1.1, 1.2, 2.5, 1.1, 0.3,
  0.5, 1.2, 2.5, 1.2, 1.3, 2.7, 1.2, 0.5, 0.6, 1.3),
  y = c(-0.5, 0, 1, 0.5, 0, 0.5, 1.5, 1, 0.5, 1, 2.1, 1.7, 1, 1.5,
  2.2, 2.1, 1.7, 2.1, 3.2, 2.8, 2.1, 2.2, 3.3, 3.2)
)

# Currently we need to manually merge the two together
datapoly <- merge(values, positions, by = c("id"))

p <- ggplot(datapoly, aes(x = x, y = y)) +
  geom_polygon(aes(fill = value, group = id))
p

# Which seems like a lot of work, but then it's easy to add on
# other features in this coordinate system, e.g.:

stream <- data.frame(
  x = cumsum(runif(50, max = 0.1)),
  y = cumsum(runif(50,max = 0.1))
)

p + geom_line(data = stream, colour = "grey30", size = 5)

# And if the positions are in longitude and latitude, you can use
# coord_map to produce different map projections.



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_polygon-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_polygon',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_polygon-up','geom_polygon-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_polygon-up','geom_polygon-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_qq
        

```{r results='asis',echo=FALSE}
 fn.src('geom_qq','ggplot2',hlp.dir)
 ```
        

```{r geom_qq, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_qq
### Title: A quantile-quantile plot
### Aliases: geom_qq stat_qq

### ** Examples




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_qq-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_qq',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_qq-up','geom_qq-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_qq-up','geom_qq-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_quantile
        

```{r results='asis',echo=FALSE}
 fn.src('geom_quantile','ggplot2',hlp.dir)
 ```
        

```{r geom_quantile, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_quantile
### Title: Quantile regression
### Aliases: geom_quantile stat_quantile

### ** Examples

m <- ggplot(mpg, aes(displ, 1 / hwy)) + geom_point()
m + geom_quantile()
m + geom_quantile(quantiles = 0.5)
q10 <- seq(0.05, 0.95, by = 0.05)
m + geom_quantile(quantiles = q10)

# You can also use rqss to fit smooth quantiles
m + geom_quantile(method = "rqss")
# Note that rqss doesn't pick a smoothing constant automatically, so
# you'll need to tweak lambda yourself
m + geom_quantile(method = "rqss", lambda = 0.1)

# Set aesthetics to fixed value
m + geom_quantile(colour = "red", size = 2, alpha = 0.5)



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_quantile-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_quantile',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_quantile-up','geom_quantile-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_quantile-up','geom_quantile-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_ribbon
        

```{r results='asis',echo=FALSE}
 fn.src('geom_ribbon','ggplot2',hlp.dir)
 ```
        

```{r geom_ribbon, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_ribbon
### Title: Ribbons and area plots
### Aliases: geom_ribbon geom_area

### ** Examples

# Generate data
huron <- data.frame(year = 1875:1972, level = as.vector(LakeHuron))
h <- ggplot(huron, aes(year))

h + geom_ribbon(aes(ymin=0, ymax=level))
h + geom_area(aes(y = level))

# Add aesthetic mappings
h +
  geom_ribbon(aes(ymin = level - 1, ymax = level + 1), fill = "grey70") +
  geom_line(aes(y = level))



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_ribbon-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_ribbon',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_ribbon-up','geom_ribbon-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_ribbon-up','geom_ribbon-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_rug
        

```{r results='asis',echo=FALSE}
 fn.src('geom_rug','ggplot2',hlp.dir)
 ```
        

```{r geom_rug, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_rug
### Title: Rug plots in the margins
### Aliases: geom_rug

### ** Examples

p <- ggplot(mtcars, aes(wt, mpg)) +
  geom_point()
p
p + geom_rug()
p + geom_rug(sides="b")    # Rug on bottom only
p + geom_rug(sides="trbl") # All four sides

# Use jittering to avoid overplotting for smaller datasets
ggplot(mpg, aes(displ, cty)) +
  geom_point() +
  geom_rug()

ggplot(mpg, aes(displ, cty)) +
  geom_jitter() +
  geom_rug(alpha = 1/2, position = "jitter")



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_rug-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_rug',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_rug-up','geom_rug-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_rug-up','geom_rug-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_smooth
        

```{r results='asis',echo=FALSE}
 fn.src('geom_smooth','ggplot2',hlp.dir)
 ```
        

```{r geom_smooth, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_smooth
### Title: Smoothed conditional means
### Aliases: geom_smooth stat_smooth

### ** Examples

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth()

# Use span to control the "wiggliness" of the default loess smoother
# The span is the fraction of points used to fit each local regression:
# small numbers make a wigglier curve, larger numbers make a smoother curve.
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth(span = 0.3)

# Instead of a loess smooth, you can use any other modelling function:
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ splines::bs(x, 3), se = FALSE)

# Smoothes are automatically fit to each group (defined by categorical
# aesthetics or the group aesthetic) and for each facet

ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +
  geom_smooth(se = FALSE, method = "lm")
ggplot(mpg, aes(displ, hwy)) +
  geom_point() +
  geom_smooth(span = 0.8) +
  facet_wrap(~drv)




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_smooth-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_smooth',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_smooth-up','geom_smooth-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_smooth-up','geom_smooth-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_spoke
        

```{r results='asis',echo=FALSE}
 fn.src('geom_spoke','ggplot2',hlp.dir)
 ```
        

```{r geom_spoke, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_spoke
### Title: Line segments parameterised by location, direction and distance
### Aliases: geom_spoke stat_spoke

### ** Examples

df <- expand.grid(x = 1:10, y=1:10)
df$angle <- runif(100, 0, 2*pi)
df$speed <- runif(100, 0, sqrt(0.1 * df$x))

ggplot(df, aes(x, y)) +
  geom_point() +
  geom_spoke(aes(angle = angle), radius = 0.5)

ggplot(df, aes(x, y)) +
  geom_point() +
  geom_spoke(aes(angle = angle, radius = speed))



        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_spoke-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_spoke',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_spoke-up','geom_spoke-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_spoke-up','geom_spoke-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_label
        

```{r results='asis',echo=FALSE}
 fn.src('geom_label','ggplot2',hlp.dir)
 ```
        

```{r geom_label, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_label
### Title: Text
### Aliases: geom_label geom_text

### ** Examples

p <- ggplot(mtcars, aes(wt, mpg, label = rownames(mtcars)))

p + geom_text()
# Avoid overlaps
p + geom_text(check_overlap = TRUE)
# Labels with background
p + geom_label()
# Change size of the label
p + geom_text(size = 10)

# Set aesthetics to fixed value
p + geom_point() + geom_text(hjust = 0, nudge_x = 0.05)
p + geom_point() + geom_text(vjust = 0, nudge_y = 0.5)
p + geom_point() + geom_text(angle = 45)

# Add aesthetic mappings
p + geom_text(aes(colour = factor(cyl)))
p + geom_text(aes(colour = factor(cyl))) +
  scale_colour_discrete(l = 40)
p + geom_label(aes(fill = factor(cyl)), colour = "white", fontface = "bold")

p + geom_text(aes(size = wt))
# Scale height of text, rather than sqrt(height)
p + geom_text(aes(size = wt)) + scale_radius(range = c(3,6))

# You can display expressions by setting parse = TRUE.  The
# details of the display are described in ?plotmath, but note that
# geom_text uses strings, not expressions.
p + geom_text(aes(label = paste(wt, "^(", cyl, ")", sep = "")),
  parse = TRUE)

# Add a text annotation
p +
  geom_text() +
  annotate("text", label = "plot mpg vs. wt", x = 2, y = 15, size = 8, colour = "red")




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_label-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_label',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_label-up','geom_label-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_label-up','geom_label-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_raster
        

```{r results='asis',echo=FALSE}
 fn.src('geom_raster','ggplot2',hlp.dir)
 ```
        

```{r geom_raster, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_raster
### Title: Rectangles
### Aliases: geom_raster geom_rect geom_tile

### ** Examples

# The most common use for rectangles is to draw a surface. You always want
# to use geom_raster here because it's so much faster, and produces
# smaller output when saving to PDF
ggplot(faithfuld, aes(waiting, eruptions)) +
 geom_raster(aes(fill = density))

# Interpolation smooths the surface & is most helpful when rendering images.
ggplot(faithfuld, aes(waiting, eruptions)) +
 geom_raster(aes(fill = density), interpolate = TRUE)

# If you want to draw arbitrary rectangles, use geom_tile() or geom_rect()
df <- data.frame(
  x = rep(c(2, 5, 7, 9, 12), 2),
  y = rep(c(1, 2), each = 5),
  z = factor(rep(1:5, each = 2)),
  w = rep(diff(c(0, 4, 6, 8, 10, 14)), 2)
)
ggplot(df, aes(x, y)) +
  geom_tile(aes(fill = z))
ggplot(df, aes(x, y)) +
  geom_tile(aes(fill = z, width = w), colour = "grey50")
ggplot(df, aes(xmin = x - w / 2, xmax = x + w / 2, ymin = y, ymax = y + 1)) +
  geom_rect(aes(fill = z, width = w), colour = "grey50")




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_raster-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_raster',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_raster-up','geom_raster-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_raster-up','geom_raster-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

## geom_violin
        

```{r results='asis',echo=FALSE}
 fn.src('geom_violin','ggplot2',hlp.dir)
 ```
        

```{r geom_violin, echo=FALSE,fig.show='hide',warning=FALSE}

        

### Name: geom_violin
### Title: Violin plot
### Aliases: geom_violin stat_ydensity

### ** Examples

p <- ggplot(mtcars, aes(factor(cyl), mpg))
p + geom_violin()




        


```
```{r}
picList=list.files(fig.dir,pattern = 'geom_violin-',full.names = T)
lp=length(picList)
# if(lp==1){
slickR(picList,slideId = 'geom_violin',width='100%',height='400px',slickOpts=list(dots=T))
#  }else{
#  slickR( rep(picList,2),
#         slideId = c('geom_violin-up','geom_violin-down'),
#                 slideIdx = list(1:lp,(lp+1):(2*lp)),
#                 slideType=rep('img',2),
#                 synchSlides = c('geom_violin-up','geom_violin-down'),
#                 slickOpts = list(list(slidesToShow=1,slidesToScroll=1),
#                 list(dots=T,slidesToScroll=1,slidesToShow=lp,centerMode=T,focusOnSelect=T)
#                 ),height=400,width='100%')
# }

```

